### PR TITLE
Update CommandLine.Options.Tests.csproj

### PR DESCRIPTION
**Pull request by asotronot**
1-) What was done in this pull request ?
Changed the target framework tag in .csproj file to run the app in .netcore 2.0

### CODE REVIEW

**Comment by Siliconrob** [comment]
Looks like nuget failure on a restore, although it did try to build with the correct framework.  You can give it another try and I can get it back to this in about 12 hours

[Build log](https://ci.appveyor.com/project/Siliconrob/commandline-options/build/1.0.8)

```
[00:00:00] Build started
[00:00:00] git clone -q https://github.com/Siliconrob/CommandLine.Options.git C:\projects\commandline-options
[00:00:01] git fetch -q origin +refs/pull/2/merge:
[00:00:02] git checkout -qf FETCH_HEAD
[00:00:02] msbuild "C:\projects\commandline-options\CommandLine.Options.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
[00:00:03] Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
[00:00:03] Copyright (C) Microsoft Corporation. All rights reserved.
[00:00:03] 
[00:00:06] C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'C:\projects\commandline-options\src\CommandLine.Options\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\projects\commandline-options\src\CommandLine.Options\CommandLine.Options.csproj]
[00:00:07] C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\projects\commandline-options\src\CommandLine.Options\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\projects\commandline-options\src\CommandLine.Options\CommandLine.Options.csproj]
[00:00:07] Command exited with code 1
```

**Comment by Siliconrob** [comment]
Delayed will look at this tonight

**Comment by asotronot** [comment]
Realized there are multiple places to change the target framework, although there are couple of places where I am unsure of whether to change it or not. I guess I'll leave this to you for the sake of not unintentionally messing up the framework settings.

**Comment by Siliconrob** [comment]
Don't get discouraged.  Can you try upgrading all the Nuget Package dependencies to 2.0 compatible targets?

**Comment by Siliconrob** [comment]
It's broke still so I will try some other stuff

**Pull request merged**
